require "digest"

puts "Seeding Snitch events..."

events = [
  {
    exception_class: "NoMethodError",
    message: "undefined method `name' for nil:NilClass",
    backtrace: ["app/models/user.rb:42:in `full_name'", "app/controllers/users_controller.rb:15:in `show'"],
    request_url: "https://myapp.com/users/123",
    request_method: "GET",
    request_params: '{"id":"123"}',
    occurrence_count: 47,
    github_issue_number: 201,
    github_issue_url: "https://github.com/owner/repo/issues/201",
    status: "open",
    first_occurred_at: 3.days.ago,
    last_occurred_at: 10.minutes.ago,
  },
  {
    exception_class: "ActiveRecord::RecordInvalid",
    message: "Validation failed: Email has already been taken",
    backtrace: ["app/services/registration_service.rb:28:in `create_user'", "app/controllers/registrations_controller.rb:10:in `create'"],
    request_url: "https://myapp.com/register",
    request_method: "POST",
    request_params: '{"user":{"email":"test@example.com","name":"Test"}}',
    occurrence_count: 12,
    github_issue_number: 198,
    github_issue_url: "https://github.com/owner/repo/issues/198",
    status: "open",
    first_occurred_at: 5.days.ago,
    last_occurred_at: 2.hours.ago,
  },
  {
    exception_class: "Redis::ConnectionError",
    message: "Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)",
    backtrace: ["app/services/cache_service.rb:15:in `fetch'", "app/controllers/products_controller.rb:8:in `index'"],
    request_url: "https://myapp.com/products",
    request_method: "GET",
    request_params: '{"page":"1"}',
    occurrence_count: 3,
    github_issue_number: 205,
    github_issue_url: "https://github.com/owner/repo/issues/205",
    status: "open",
    first_occurred_at: 1.day.ago,
    last_occurred_at: 45.minutes.ago,
  },
  {
    exception_class: "Net::ReadTimeout",
    message: "Net::ReadTimeout with #<TCPSocket:(closed)>",
    backtrace: ["app/services/payment_gateway.rb:55:in `charge'", "app/controllers/orders_controller.rb:32:in `create'"],
    request_url: "https://myapp.com/orders",
    request_method: "POST",
    request_params: '{"order":{"product_id":"42","quantity":"1"}}',
    occurrence_count: 8,
    github_issue_number: nil,
    github_issue_url: nil,
    status: "open",
    first_occurred_at: 2.days.ago,
    last_occurred_at: 6.hours.ago,
  },
  {
    exception_class: "ArgumentError",
    message: "wrong number of arguments (given 3, expected 2)",
    backtrace: ["app/helpers/formatting_helper.rb:12:in `format_currency'", "app/views/invoices/show.html.erb:25"],
    request_url: "https://myapp.com/invoices/456",
    request_method: "GET",
    request_params: '{"id":"456"}',
    occurrence_count: 1,
    github_issue_number: 210,
    github_issue_url: "https://github.com/owner/repo/issues/210",
    status: "open",
    first_occurred_at: 30.minutes.ago,
    last_occurred_at: 30.minutes.ago,
  },
  # Closed exceptions
  {
    exception_class: "TypeError",
    message: "no implicit conversion of String into Integer",
    backtrace: ["app/models/report.rb:88:in `generate'", "app/controllers/reports_controller.rb:20:in `create'"],
    request_url: "https://myapp.com/reports",
    request_method: "POST",
    request_params: '{"report":{"type":"monthly"}}',
    occurrence_count: 22,
    github_issue_number: 180,
    github_issue_url: "https://github.com/owner/repo/issues/180",
    status: "closed",
    first_occurred_at: 2.weeks.ago,
    last_occurred_at: 4.days.ago,
  },
  {
    exception_class: "Encoding::UndefinedConversionError",
    message: "\"\\xC3\" from ASCII-8BIT to UTF-8",
    backtrace: ["app/services/csv_importer.rb:34:in `parse_row'", "app/controllers/imports_controller.rb:18:in `create'"],
    request_url: "https://myapp.com/imports",
    request_method: "POST",
    request_params: '{"file":"data.csv"}',
    occurrence_count: 5,
    github_issue_number: 175,
    github_issue_url: "https://github.com/owner/repo/issues/175",
    status: "closed",
    first_occurred_at: 3.weeks.ago,
    last_occurred_at: 1.week.ago,
  },
  # Ignored exceptions
  {
    exception_class: "ActionController::InvalidAuthenticityToken",
    message: "ActionController::InvalidAuthenticityToken",
    backtrace: ["app/controllers/application_controller.rb:1:in `verify_authenticity_token'"],
    request_url: "https://myapp.com/sessions",
    request_method: "POST",
    request_params: '{}',
    occurrence_count: 156,
    github_issue_number: 150,
    github_issue_url: "https://github.com/owner/repo/issues/150",
    status: "ignored",
    first_occurred_at: 1.month.ago,
    last_occurred_at: 1.hour.ago,
  },
  {
    exception_class: "ActionController::BadRequest",
    message: "Invalid query parameters",
    backtrace: ["app/controllers/search_controller.rb:5:in `index'"],
    request_url: "https://myapp.com/search?q=%00",
    request_method: "GET",
    request_params: '{"q":"\\u0000"}',
    occurrence_count: 89,
    github_issue_number: 160,
    github_issue_url: "https://github.com/owner/repo/issues/160",
    status: "ignored",
    first_occurred_at: 3.weeks.ago,
    last_occurred_at: 2.days.ago,
  },
]

events.each do |attrs|
  fingerprint = Digest::SHA256.hexdigest("#{attrs[:exception_class]}:#{attrs[:backtrace]&.first}")
  Snitch::Event.create!(attrs.merge(fingerprint: fingerprint))
end

puts "Created #{Snitch::Event.count} events (#{Snitch::Event.open.count} open, #{Snitch::Event.closed.count} closed, #{Snitch::Event.ignored.count} ignored)"
